"""empty message

Revision ID: 2fd70798138d
Revises: 84a9c586768f
Create Date: 2020-06-15 08:49:08.917375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd70798138d'
down_revision = '84a9c586768f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('code', sa.String(), nullable=True))
    op.add_column('survey', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'is_public')
    op.drop_column('survey', 'code')
    # ### end Alembic commands ###
