"""empty message

Revision ID: 5c4da37ae39c
Revises: df2e7a9cef2e
Create Date: 2020-04-25 11:29:14.693414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4da37ae39c'
down_revision = 'df2e7a9cef2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionnaire', 'description')
    # ### end Alembic commands ###
