"""empty message

Revision ID: 84a9c586768f
Revises: 581e04323768
Create Date: 2020-05-12 14:31:47.204402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a9c586768f'
down_revision = '581e04323768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'position')
    # ### end Alembic commands ###
