"""empty message

Revision ID: cae4f86f0af6
Revises: 315bb10e127c
Create Date: 2020-06-18 17:30:11.148906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae4f86f0af6'
down_revision = '315bb10e127c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('is_actual', sa.Boolean(), nullable=True))
    op.drop_column('survey', 'is_public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('survey', 'is_actual')
    # ### end Alembic commands ###
