name: Just check if project can built

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      max-parallel: 4
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install --prefix frontend/
      - name: Build page
        run: npm install --prefix frontend/
