name: Just check if project can built

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: cd frontend && npm install
    - run: cd frontend && npm run build --if-present
